apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-cve-2021-30049-xss
  namespace: default    #Change with your namespace
spec:
  tags: ["SysAID","CVE","CVE-2021-30049","XSS"]
  message: "Alert! Unknown user tried to access KeepAlive.jsp script"
  selector:
    matchLabels:
      app: SysAID    #Change with your pod labels
  process:
    severity: 6
    matchDirectories:
    - dir: /var/www/html/KeepAlive.jsp
      recursive: true
    action: Block
  file:
    severity: 6
    matchDirectories:
    - dir: /var/www/html/KeepAlive.jsp
      readOnly: false
      recursive: true
    action: Block
